### ISSUE TITLE
Validating Webhook Event Signatures

### ISSUE THREAD

**Issue by k-s-t-i** [onfido/onfido-python#17]
I am currently facing an issue where the Webhook event signatures are failing. I am using the following snippet of code:
```python
onfido_webhook_token: str = get_onfido_webhook_token()
signature = request.headers['X-SHA2-Signature']
raw_request = (await request.body()).decode('utf-8')
WebhookEventVerifier(webhook_token=onfido_webhook_token).read_payload(raw_event=raw_request, signature=signature)
```

It may be that I am not handling encoding correctly, anyone spot an issue?

**Comment by k-s-t-i** [comment]
@superdevx64?

**Comment by superdevx64** [comment]
Hey @k-s-t-i I'm afraid I'm not with Onfido any more but if you open a ticket at api@onfido.com then this should get more attention. At first glance I can't see anything wrong with your snippet I'm afraid but if you provide the specific error(s) that are being returned to Onfido Support then they'll direct the question appropriately internally :+1:

**Comment by k-s-t-i** [comment]
Thanks @superdevx64! Closing and emailing them.
