### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by hobochild** [onfido/onfido-python#5]
It'd be great to be able to configure the HTTP clients timeout. I'm happy to help with a PR if needed.

**Comment by superdevx64** [comment]
Hi @hobochild, apologies for the delay in getting back to you. 

Thank you very much for your suggestion. You're very welcome to raise a PR for this if you have the bandwidth, or else I can look into this myself as soon as time permits. I'll let you know in another comment here as soon as I start working on it, if I don't hear from you.

**Comment by hobochild** [comment]
Great thanks, I'm also tied up with things at the moment, I'll let you know if I get around to it before you do.

**Comment by superdevx64** [comment]
Hi @hobochild just to let you know I'll look at this today and aim to raise a PR shortly
